version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'kernel-postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=afc848c316af1a89d49826c5ae9d00ed769415f3'
      - 'POSTGRES_PASSWORD=7c4a8d09ca3762af61e59520943dc26494f8941b'
      - 'POSTGRES_DB=kernel-users'
    networks:
      - kernel-network

  kernel-backend:
    build: ./
    container_name: 'kernel-backend'
    ports:
      - 8080:8080
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://kernel-postgres:5432/kernel-users'
      - 'SPRING_DATASOURCE_USERNAME=afc848c316af1a89d49826c5ae9d00ed769415f3'
      - 'SPRING_DATASOURCE_PASSWORD=7c4a8d09ca3762af61e59520943dc26494f8941b'
    networks:
      - kernel-network

  jitsi:
    image: jitsi/jitsi-meet:latest
    restart: always
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - ./jitsi/config:/config

networks:
  kernel-network: